[project]
name = "ArcheoGeneticMap"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["Kyle Larkin"]
version = "0.1.0"
license = "MIT"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
julia = "1.9"
